version: "3.9"

services:

  mysql:
    image: mysql:8.0.19
    ports:
     - 3306:3306
    volumes:
     - $PWD/initialize_db.sql:/docker-entrypoint-initdb.d/initialize_db.sql
    environment:
      - MYSQL_DATABASE=hackerrank
      - MYSQL_ROOT_PASSWORD=password
